exclude: (build|dist)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-case-conflict
    - id: detect-private-key
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        files: ^(src|tests)/
        args:
          - --in-place
          - --max-line-length=79

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(src|tests)/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(src|tests)/
        args:
          - --max-line-length=79
