name: Dependabot Actions

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
    - dependabot/pip/**
  pull_request:
    branches:
    - dependabot/pip/**

env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: 1.8.2

jobs:
  run:
    name: Update requirements.txt and lock file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - uses: ./.github/actions/setup-poetry-action
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
        python-version: ${{ env.PYTHON_VERSION }}
        install-dependencies: false
    - name: Update dependencies
      run: |
        poetry lock --no-update
        poetry export -f requirements.txt --output requirements.txt --without-hashes
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update requirements.txt
        branch: ${{ github.head_ref }}
